#!/usr/bin/env python
import sys

twl = {}
with open('twl') as twlfile:
    for line in twlfile:
        twl[line.rstrip()] = 0

badfield0 = None
for line in sys.stdin:
    fields = line.split()
    if fields[0] == badfield0:
        continue
    word = fields[0].split('_')[0].lower()
    try:
        twl[word] += int(fields[2])
    except KeyError:
        badfield0 = fields[0]

for k,v in twl.iteritems():
    if v > 0:
        print k, v
